default: &default
  twitter_consumer_key: "xaQEoXHuw2K4iTkhZfEyJXOTX"
  twitter_consumer_secret: "4216LOIZ7mD0SpetemhqoMrKMYiyGLFLGajVNtITrx1SE1WT2D"
  secret_key_base: f9848c5fb3d65ad8785ce0771c74b09a2671eb63e3e3ea80c955a841735319549513162c338497eff15c66ff103c37cb4aba4149e13ef8ba7346a4b828b7573d

  
development:
  <<: *default

test:
  <<: *default

production:
  twitter_consumer_key:  <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret:  <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  secret_key_base:  <%= ENV["SECRET_KEY_BASE"] %>