default: &default
  twitter_consumer_key: "xaQEoXHuw2K4iTkhZfEyJXOTX"
  twitter_consumer_secret: "4216LOIZ7mD0SpetemhqoMrKMYiyGLFLGajVNtITrx1SE1WT2D"

development:
  <<: *default

test:
  <<: *default

production:
  twitter_consumer_key:  <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret:  <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  secret_key_base:  <%= ENV["SECRET_KEY_BASE"] %>